### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by MatteoBellarasa** [rahulrathore44/Trx2Excel#4]
Eccezione non gestita: System.InvalidOperationException: A worksheet with this name already exists in the workbook : GeoPlus.TestSuites.Recapito.Rec
   in OfficeOpenXml.ExcelWorksheets.AddSheet(String Name, Boolean isChart, Nullable`1 chartType, ExcelPivotTable pivotTableSource)
   in OfficeOpenXml.ExcelWorksheets.Add(String Name)
   in Trx2Excel.ExcelUtils.ExcelWriter.AddSheetToExcel(Dictionary`2 filteredData, ExcelPackage package, String nameSpace) in C:\Users\matbellara\Documents\TRX2EXCEL\Trx2Excel\Trx2Excel\ExcelUtils\ExcelWriter.cs:riga 63
   in Trx2Excel.ExcelUtils.ExcelWriter.WriteToExcel(List`1 resultList) in C:\Users\matbellara\Documents\TRX2EXCEL\Trx2Excel\Trx2Excel\ExcelUtils\ExcelWriter.cs:riga 55
   in Trx2Excel.Program.Main(String[] args) in C:\Users\matbellara\Documents\TRX2EXCEL\Trx2Excel\Trx2Excel\Program.cs:riga 28

**Comment by rahulrathore44** [comment]
@MatteoBellarasa Kindly share the sample `trx` file to reproduce this issue.

**Comment by MatteoBellarasa** [comment]
Dear Rahul,

I cannot at all show you the document due to privacy reasons.

Sorry,

Matteo B.

Il sab 24 lug 2021, 18:53 Rahul Singh Rathore ***@***.***> ha
scritto:

**Comment by rahulrathore44** [comment]
This issue is fixed and merged as part of branch `bugfix/sheet_name`
